// Same visual system as templates/approvalEmail.js (ink #161A26, gold
// #C9974B, teal #2F6E63, hand-built inline-styled HTML for email
// client compatibility) — widened to fit a details table instead of a
// single paragraph + button.
export function informationSetupEmail({ employee, submitted }) {
  const fullName = `${employee.firstName} ${employee.lastName}`;
  const subject = `Information Setup submitted — ${fullName} (${employee.employeeId})`;

  const personalRows = [
    ["First name", submitted.firstName],
    ["Last name", submitted.lastName],
    ["Phone", submitted.phone],
    ["Email", submitted.email],
    ["Mailing address", submitted.address],
  ];
  const employmentRows = [
    ["Employee ID", employee.employeeId],
    ["Department", employee.department],
    ["Job title", employee.jobTitle],
    ["Manager", employee.manager],
  ];
  const paymentRows = [
    ["Account holder name", submitted.accountHolder],
    ["Bank name", submitted.bankName],
    ["Account number", submitted.accountNumber],
    ["Routing number", submitted.routingNumber],
  ];

  const text = `New Information Setup submission — ${fullName} (${employee.employeeId})

PERSONAL INFORMATION
${personalRows.map(([l, v]) => `${l}: ${v || "—"}`).join("\n")}

EMPLOYMENT INFORMATION
${employmentRows.map(([l, v]) => `${l}: ${v || "—"}`).join("\n")}

PAYMENT INFORMATION
${paymentRows.map(([l, v]) => `${l}: ${v || "—"}`).join("\n")}

— Growverde Solutions employee portal`;

  const html = `<!doctype html>
<html>
  <body style="margin:0;padding:0;background:#FAFAF7;font-family:Arial,Helvetica,sans-serif;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#FAFAF7;padding:32px 16px;">
      <tr>
        <td align="center">
          <table role="presentation" width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#FFFFFF;border:1px solid #E4E1D9;border-radius:14px;overflow:hidden;">

            <tr>
              <td style="background:#161A26;padding:28px 32px;">
                <table role="presentation" cellpadding="0" cellspacing="0">
                  <tr>
                    <td style="border:1.5px solid rgba(255,255,255,0.7);border-radius:6px;padding:6px 14px;">
                      <div style="font-size:15px;font-weight:800;letter-spacing:-0.02em;color:#FFFFFF;font-family:Arial,Helvetica,sans-serif;">
                        GROW<span style="color:#A8CBC3;">VERDE</span>
                      </div>
                      <div style="font-size:9px;font-weight:700;letter-spacing:0.22em;text-transform:uppercase;color:#A8CBC3;margin-top:2px;">
                        Solutions
                      </div>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>

            <tr>
              <td style="padding:36px 32px 8px;">
                <p style="margin:0 0 6px;font-size:12px;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;color:#2F6E63;">
                  New Submission
                </p>
                <h1 style="margin:0 0 18px;font-size:22px;line-height:1.3;color:#161A26;font-family:Georgia,'Times New Roman',serif;">
                  Information Setup — ${escapeHtml(fullName)}
                </h1>
                <p style="margin:0 0 8px;font-size:14.5px;line-height:1.65;color:#3F4451;">
                  ${escapeHtml(fullName)} (${escapeHtml(employee.employeeId)}) just submitted their Information
                  Setup form from the employee portal. Full details are below.
                </p>
              </td>
            </tr>

            <tr>
              <td style="padding:0 32px 12px;">
                <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
                  ${section("Personal Information", personalRows)}
                  ${section("Employment Information", employmentRows)}
                  ${section("Payment Information", paymentRows)}
                </table>
              </td>
            </tr>

            <tr>
              <td style="padding:20px 32px 32px;border-top:1px solid #E4E1D9;">
                <p style="margin:0;font-size:12px;color:#9A9384;line-height:1.6;">
                  This is an automated message generated by the Growverde Solutions
                  employee portal — please don't reply directly to it.
                </p>
              </td>
            </tr>

          </table>
        </td>
      </tr>
    </table>
  </body>
</html>`;

  return { subject, text, html };
}

function section(title, rows, note) {
  return `
    <tr>
      <td colspan="2" style="padding:18px 0 8px;font-size:12px;font-weight:700;letter-spacing:0.08em;text-transform:uppercase;color:#161A26;border-top:1px solid #E4E1D9;">
        ${escapeHtml(title)}
      </td>
    </tr>
    ${rows.map(([label, value]) => fieldRow(label, value)).join("")}
    ${note ? `<tr><td colspan="2" style="padding:6px 0 0;font-size:11.5px;color:#9A9384;line-height:1.5;">${escapeHtml(note)}</td></tr>` : ""}
  `;
}

function fieldRow(label, value) {
  const display = value ? escapeHtml(value) : '<span style="color:#C8C2B4;">—</span>';
  return `
    <tr>
      <td style="padding:7px 12px 7px 0;border-bottom:1px solid #F2F1EC;font-size:12px;font-weight:600;letter-spacing:0.03em;text-transform:uppercase;color:#9A9384;width:180px;vertical-align:top;white-space:nowrap;">
        ${escapeHtml(label)}
      </td>
      <td style="padding:7px 0;border-bottom:1px solid #F2F1EC;font-size:14px;color:#161A26;vertical-align:top;">
        ${display}
      </td>
    </tr>`;
}

function escapeHtml(value = "") {
  return String(value).replace(/[&<>"']/g, (c) => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
  }[c]));
}
