// Same visual system as templates/approvalEmail.js (ink #161A26, gold
// #C9974B, teal #2F6E63, hand-built inline-styled HTML for email
// client compatibility). Unlike the employee-portal templates, there's
// no signed-in "employee" here — this is a public, unauthenticated
// submission from the careers site.
export function resumeSubmissionEmail({ firstName, lastName, email, phone, fieldOfInterest, experienceLevel, note, fileName }) {
  const subject = `Resume submission — ${firstName} ${lastName}`;

  const rows = [
    ["First name", firstName],
    ["Last name", lastName],
    ["Email", email],
    ["Phone", phone],
    ["Field of interest", fieldOfInterest],
    ["Experience level", experienceLevel],
    ["Note", note],
  ];

  const text = `New resume submission — ${firstName} ${lastName}

${rows.map(([l, v]) => `${l}: ${v || "—"}`).join("\n")}

Resume file attached: ${fileName}

— Growverde Solutions careers site`;

  const html = `<!doctype html>
<html>
  <body style="margin:0;padding:0;background:#FAFAF7;font-family:Arial,Helvetica,sans-serif;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#FAFAF7;padding:32px 16px;">
      <tr>
        <td align="center">
          <table role="presentation" width="560" cellpadding="0" cellspacing="0" style="max-width:560px;width:100%;background:#FFFFFF;border:1px solid #E4E1D9;border-radius:14px;overflow:hidden;">

            <tr>
              <td style="background:#161A26;padding:28px 32px;">
                <table role="presentation" cellpadding="0" cellspacing="0">
                  <tr>
                    <td style="border:1.5px solid rgba(255,255,255,0.7);border-radius:6px;padding:6px 14px;">
                      <div style="font-size:15px;font-weight:800;letter-spacing:-0.02em;color:#FFFFFF;font-family:Arial,Helvetica,sans-serif;">
                        GROW<span style="color:#A8CBC3;">VERDE</span>
                      </div>
                      <div style="font-size:9px;font-weight:700;letter-spacing:0.22em;text-transform:uppercase;color:#A8CBC3;margin-top:2px;">
                        Solutions
                      </div>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>

            <tr>
              <td style="padding:36px 32px 8px;">
                <p style="margin:0 0 6px;font-size:12px;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;color:#2F6E63;">
                  New Submission — Careers Site
                </p>
                <h1 style="margin:0 0 18px;font-size:22px;line-height:1.3;color:#161A26;font-family:Georgia,'Times New Roman',serif;">
                  ${escapeHtml(firstName)} ${escapeHtml(lastName)} submitted a resume
                </h1>
                <p style="margin:0 0 24px;font-size:14.5px;line-height:1.65;color:#3F4451;">
                  Submitted through the public "Submit Your Resume" page. The resume file is attached to this email.
                </p>
              </td>
            </tr>

            <tr>
              <td style="padding:0 32px 8px;">
                <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
                  ${rows.map(([label, value]) => fieldRow(label, value)).join("")}
                  <tr>
                    <td style="padding:8px 0;border-bottom:1px solid #F2F1EC;font-size:12px;font-weight:600;letter-spacing:0.03em;text-transform:uppercase;color:#9A9384;width:160px;vertical-align:top;">
                      Resume file
                    </td>
                    <td style="padding:8px 0;border-bottom:1px solid #F2F1EC;font-size:14px;color:#161A26;vertical-align:top;">
                      📎 ${escapeHtml(fileName)} (attached)
                    </td>
                  </tr>
                </table>
              </td>
            </tr>

            <tr>
              <td style="padding:20px 32px 32px;border-top:1px solid #E4E1D9;">
                <p style="margin:0;font-size:12px;color:#9A9384;line-height:1.6;">
                  This is an automated message generated by the Growverde Solutions
                  careers site — please don't reply directly to it.
                </p>
              </td>
            </tr>

          </table>
        </td>
      </tr>
    </table>
  </body>
</html>`;

  return { subject, text, html };
}

function fieldRow(label, value) {
  const display = value ? escapeHtml(value) : '<span style="color:#C8C2B4;">—</span>';
  return `
    <tr>
      <td style="padding:8px 0;border-bottom:1px solid #F2F1EC;font-size:12px;font-weight:600;letter-spacing:0.03em;text-transform:uppercase;color:#9A9384;width:160px;vertical-align:top;">
        ${escapeHtml(label)}
      </td>
      <td style="padding:8px 0;border-bottom:1px solid #F2F1EC;font-size:14px;color:#161A26;vertical-align:top;">
        ${display}
      </td>
    </tr>`;
}

function escapeHtml(value = "") {
  return String(value).replace(/[&<>"']/g, (c) => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
  }[c]));
}
