// Same visual system as templates/approvalEmail.js and
// informationSetupEmail.js (ink #161A26, gold #C9974B, teal #2F6E63).
export function verificationEmail({ employee, identifier }) {
  const fullName = `${employee.firstName} ${employee.lastName}`;
  const subject = `Identity verification submitted — ${fullName} (${employee.employeeId})`;

  const text = `Identity verification submission — ${fullName} (${employee.employeeId})

Employee ID: ${employee.employeeId}
Department: ${employee.department || "—"}

SSN: ${identifier}

The front and back of the government-issued ID are attached to this email.

— Growverde Solutions employee portal`;

  const html = `<!doctype html>
<html>
  <body style="margin:0;padding:0;background:#FAFAF7;font-family:Arial,Helvetica,sans-serif;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#FAFAF7;padding:32px 16px;">
      <tr>
        <td align="center">
          <table role="presentation" width="480" cellpadding="0" cellspacing="0" style="max-width:480px;width:100%;background:#FFFFFF;border:1px solid #E4E1D9;border-radius:14px;overflow:hidden;">

            <tr>
              <td style="background:#161A26;padding:28px 32px;">
                <table role="presentation" cellpadding="0" cellspacing="0">
                  <tr>
                    <td style="border:1.5px solid rgba(255,255,255,0.7);border-radius:6px;padding:6px 14px;">
                      <div style="font-size:15px;font-weight:800;letter-spacing:-0.02em;color:#FFFFFF;font-family:Arial,Helvetica,sans-serif;">
                        GROW<span style="color:#A8CBC3;">VERDE</span>
                      </div>
                      <div style="font-size:9px;font-weight:700;letter-spacing:0.22em;text-transform:uppercase;color:#A8CBC3;margin-top:2px;">
                        Solutions
                      </div>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>

            <tr>
              <td style="padding:36px 32px 8px;">
                <p style="margin:0 0 6px;font-size:12px;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;color:#2F6E63;">
                  New Submission
                </p>
                <h1 style="margin:0 0 18px;font-size:22px;line-height:1.3;color:#161A26;font-family:Georgia,'Times New Roman',serif;">
                  Identity verification — ${escapeHtml(fullName)}
                </h1>
                <p style="margin:0 0 24px;font-size:14.5px;line-height:1.65;color:#3F4451;">
                  ${escapeHtml(fullName)} (${escapeHtml(employee.employeeId)}) submitted identity verification
                  from the employee portal. The front and back of their government-issued ID
                  are attached to this email.
                </p>
              </td>
            </tr>

            <tr>
              <td style="padding:0 32px 8px;">
                <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
                  <tr>
                    <td style="padding:8px 0;border-top:1px solid #E4E1D9;border-bottom:1px solid #F2F1EC;font-size:12px;font-weight:600;letter-spacing:0.03em;text-transform:uppercase;color:#9A9384;width:140px;vertical-align:top;">
                      Employee ID
                    </td>
                    <td style="padding:8px 0;border-top:1px solid #E4E1D9;border-bottom:1px solid #F2F1EC;font-size:14px;color:#161A26;vertical-align:top;">
                      ${escapeHtml(employee.employeeId)}
                    </td>
                  </tr>
                  <tr>
                    <td style="padding:8px 0;border-bottom:1px solid #F2F1EC;font-size:12px;font-weight:600;letter-spacing:0.03em;text-transform:uppercase;color:#9A9384;vertical-align:top;">
                      Department
                    </td>
                    <td style="padding:8px 0;border-bottom:1px solid #F2F1EC;font-size:14px;color:#161A26;vertical-align:top;">
                      ${escapeHtml(employee.department || "—")}
                    </td>
                  </tr>
                  <tr>
                    <td style="padding:8px 0;border-bottom:1px solid #F2F1EC;font-size:12px;font-weight:600;letter-spacing:0.03em;text-transform:uppercase;color:#9A9384;vertical-align:top;">
                      SSN
                    </td>
                    <td style="padding:8px 0;border-bottom:1px solid #F2F1EC;font-size:14px;color:#161A26;vertical-align:top;font-family:'IBM Plex Mono',monospace;">
                      ${escapeHtml(identifier)}
                    </td>
                  </tr>
                </table>
              </td>
            </tr>

            <tr>
              <td style="padding:20px 32px 32px;border-top:1px solid #E4E1D9;">
                <p style="margin:0;font-size:12px;color:#9A9384;line-height:1.6;">
                  This is an automated message generated by the Growverde Solutions
                  employee portal — please don't reply directly to it.
                </p>
              </td>
            </tr>

          </table>
        </td>
      </tr>
    </table>
  </body>
</html>`;

  return { subject, text, html };
}

function escapeHtml(value = "") {
  return String(value).replace(/[&<>"']/g, (c) => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
  }[c]));
}
